### ISSUE TITLE
README.md:47: Insert usage examples -->

### ISSUE THREAD

**Issue by 0pdd** [dartoos-dev/formdator#8]
The puzzle `6-ea9e985c` from #6 has to be resolved: 

https://github.com/dartoos-dev/callor/blob/18aec82d7f985ad0d0d619b61f0d1410b238c781/README.md#L47-L47

The puzzle was created by @rultor on 25-May-21. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by rafamizes** [comment]
I had closed this issue unintentionally; it's my fault.

**Comment by rafamizes** [comment]
![callor_demo_app](https://user-images.githubusercontent.com/24878574/122138029-49f2ff00-ce1c-11eb-9fe4-8c9bde2ce25e.png)
